default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "freight_user" } if Rails.env.production? %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "freight_password" } if Rails.env.production? %>

development:
  <<: *default
  database: freight_forwarder_development

test:
  <<: *default
  database: freight_forwarder_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "freight_forwarder_production" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "freight_user" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "freight_password" } %>

# Action Cable configuration for solid_cable
cable:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "freight_forwarder_production" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "freight_user" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "freight_password" } %>

# Solid Queue configuration
queue:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "freight_forwarder_production" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "freight_user" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "freight_password" } %>

# Solid Cache configuration
cache:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "freight_forwarder_production" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "freight_user" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "freight_password" } %>
